Repository teamGreenGreen/CookieRunClient, pull requests merged in 2024-02, with the labels that each got.

#34 TestMap Scene에 타일 맵 생성
  Assets/Resources/InGame/Materials.meta
  Assets/Resources/InGame/Materials/Land1.mat
  Assets/Resources/InGame/Materials/Land1.mat.meta
  Assets/Resources/InGame/TilePalette.prefab
  Assets/Resources/InGame/effect_ingame1stGrade.png
  Assets/Resources/InGame/effect_ingame1stGrade.png.meta
  Assets/Resources/UI/L10n_imgTxt_result.png
  Assets/Resources/UI/L10n_imgTxt_result.png.meta
  Assets/Resources/UI/img_pointmission_ribbon1.png
  Assets/Resources/UI/img_pointmission_ribbon1.png.meta
  Assets/Scenes/TestMap.unity
Labels: client

#41 플레이어와 아이템 충돌 시 점수, 재화, 알파벳 표시
  Assets/Resources/Obj/Flower3.prefab
  Assets/Resources/Obj/Flower3.prefab.meta
  Assets/Resources/Obj/GoldCoin.prefab
  Assets/Resources/Obj/JellyB.prefab
  Assets/Resources/Obj/JellyBean.prefab
  Assets/Resources/Obj/JellyBearBig.prefab
  Assets/Resources/Obj/JellyBearPink.prefab
  Assets/Resources/Obj/JellyBearYellow.prefab
  Assets/Resources/Obj/JellyE.prefab
  Assets/Resources/Obj/JellyI.prefab
  Assets/Resources/Obj/JellyM.prefab
  Assets/Resources/Obj/JellyN.prefab
  Assets/Resources/Obj/JellyO.prefab
  Assets/Resources/Obj/JellyS.prefab
  Assets/Resources/Obj/JellyT.prefab
  Assets/Resources/Obj/JellyU.prefab
  Assets/Resources/Obj/Land1.prefab
  Assets/Resources/Obj/Land1.prefab.meta
  Assets/Resources/Obj/Land2.prefab
  Assets/Resources/Obj/Land3.prefab
  Assets/Resources/Obj/Land3.prefab.meta
  Assets/Resources/Obj/Land4.prefab
  Assets/Resources/Obj/Land4.prefab.meta
  Assets/Resources/Obj/SilverCoin.prefab
  Assets/Scenes/TestMap.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Item.cs
  Assets/Scripts/PlayerLogic/Player.cs
Labels: client

#48 플레이어와 장애물 충돌 시 플레이어 HP 감소
  Assets/Prefabs/InGame/Bee.prefab
  Assets/Prefabs/InGame/BigEarthworm.prefab
  Assets/Prefabs/InGame/SmallEarthworm.prefab
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Obstacle/Obstacle.cs
Labels: client

#60 HttpManager의 post 요청을 종류별로 만듬
  Assets/Scripts/Auth/Account.cs
  Assets/Scripts/Auth/Login.cs
  Assets/Scripts/HttpManager.cs
Labels: enhancement

#61 Connect UI friend#56
  Assets/Animation/LobbyMain.meta
  Assets/Animation/LobbyMain/Lemon.meta
  Assets/Animation/LobbyMain/Pancake.meta
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie.png
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie.png.meta
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie_Wink.png
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie_Wink.png.meta
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie_Wink_0.controller
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie_Wink_0.controller.meta
  Assets/Animation/LobbyMain/Pancake/Pancake_Face.anim
  Assets/Animation/LobbyMain/Pancake/Pancake_Face.anim.meta
  Assets/Prefabs/UI/FriendListElement.prefab
  Assets/Prefabs/UI/FriendListElement.prefab.meta
  Assets/Prefabs/UI/FriendReqListElement.prefab
  Assets/Prefabs/UI/FriendReqListElement.prefab.meta
  Assets/Scenes/LobbyScene.unity
  Assets/Scripts/DAO.meta
  Assets/Scripts/DAO/GameServer.meta
  Assets/Scripts/DAO/GameServer/Friend.meta
  Assets/Scripts/DAO/GameServer/Friend/FriendList_DAO.cs
  Assets/Scripts/DAO/GameServer/Friend/FriendList_DAO.cs.meta
  Assets/Scripts/DAO/GameServer/Friend/FriendRequestList_DAO.cs
  Assets/Scripts/DAO/GameServer/Friend/FriendRequestList_DAO.cs.meta
  Assets/Scripts/DTO/GameServer.meta
  Assets/Scripts/DTO/GameServer/Friend.meta
  Assets/Scripts/DTO/GameServer/Friend/FriendDelete_DTO.cs
  Assets/Scripts/DTO/GameServer/Friend/FriendDelete_DTO.cs.meta
  Assets/Scripts/DTO/GameServer/Friend/FriendList_DTO.cs
  Assets/Scripts/DTO/GameServer/Friend/FriendList_DTO.cs.meta
  Assets/Scripts/DTO/GameServer/Friend/FriendRequestAccept_DTO.cs
  Assets/Scripts/DTO/GameServer/Friend/FriendRequestAccept_DTO.cs.meta
  Assets/Scripts/DTO/GameServer/Friend/FriendRequestDeny_DTO.cs
  Assets/Scripts/DTO/GameServer/Friend/FriendRequestDeny_DTO.cs.meta
  Assets/Scripts/DTO/GameServer/Friend/FriendRequestList_DTO.cs
  Assets/Scripts/DTO/GameServer/Friend/FriendRequestList_DTO.cs.meta
  Assets/Scripts/DTO/GameServer/Friend/FriendRequest_DTO.cs
  Assets/Scripts/DTO/GameServer/Friend/FriendRequest_DTO.cs.meta
  Assets/Scripts/Friend.meta
  Assets/Scripts/Friend/FriendDelete.cs
  Assets/Scripts/Friend/FriendDelete.cs.meta
  Assets/Scripts/Friend/FriendElementUI.cs
  Assets/Scripts/Friend/FriendElementUI.cs.meta
  Assets/Scripts/Friend/FriendList.cs
  Assets/Scripts/Friend/FriendList.cs.meta
  Assets/Scripts/Friend/FriendRequest.cs
  Assets/Scripts/Friend/FriendRequest.cs.meta
  Assets/Scripts/Friend/FriendRequestAccept.cs
  Assets/Scripts/Friend/FriendRequestAccept.cs.meta
  Assets/Scripts/Friend/FriendRequestDeny.cs
  Assets/Scripts/Friend/FriendRequestDeny.cs.meta
  Assets/Scripts/Friend/FriendRequestElementUI.cs
  Assets/Scripts/Friend/FriendRequestElementUI.cs.meta
  Assets/Scripts/Friend/FriendRequestList.cs
  Assets/Scripts/Friend/FriendRequestList.cs.meta
  Assets/Scripts/ScrollingObject.cs
Labels: client

#62 cookieMainImg
  Assets/Animation.meta
  Assets/Animation/LobbyMain.meta
  Assets/Animation/LobbyMain/Lemon.meta
  Assets/Animation/LobbyMain/Pancake.meta
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie_Wink.png
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie_Wink_0.controller
  Assets/Animation/LobbyMain/Pancake/Pancake Cookie_Wink_0.controller.meta
  Assets/Animation/LobbyMain/Pancake/Pancake_Face.anim
  Assets/Animation/LobbyMain/Pancake/Pancake_Face.anim.meta
  Assets/Resources/Cookie/StandCookie/blueberrypieCookie_stand.png
  Assets/Resources/Cookie/StandCookie/blueberrypieCookie_stand.png.meta
  Assets/Resources/Cookie/StandCookie/braveCookie_stand.png
  Assets/Resources/Cookie/StandCookie/braveCookie_stand.png.meta
  Assets/Resources/Cookie/StandCookie/cookie0001_stand.png
  Assets/Resources/Cookie/StandCookie/cookie0052_stand.png
  Assets/Resources/Cookie/StandCookie/cookie0052_stand.png.meta
  Assets/Resources/Cookie/StandCookie/cookie0069_stand 1.png
  Assets/Resources/Cookie/StandCookie/cookie0148_stand.png
  Assets/Resources/Cookie/StandCookie/cookie0148_stand.png.meta
  Assets/Resources/Cookie/StandCookie/lemonCookie_stand.png
  Assets/Resources/Cookie/StandCookie/lemonCookie_stand.png.meta
  Assets/Resources/Cookie/StandCookie/pancakeCookie_stand.png
  Assets/Resources/Cookie/StandCookie/pancakeCookie_stand.png.meta
  Assets/Scenes/LobbyScene.unity
Labels: client

#64 User info
  Assets/Scenes/TestMap.unity
  Assets/Scripts/DTO/GameResult.cs
  Assets/Scripts/DTO/GameResult.cs.meta
  Assets/Scripts/DTO/UserInfo.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/LoadSceneManager.cs
  Assets/Scripts/PlayerLogic/Player.cs
  Assets/Scripts/UI/LobbyUIManager.cs
  Assets/Scripts/UI/LobbyUIManager.cs.meta
Labels: client

#67 #66cookieShop
  Assets/Scripts/DTO/UserInfo.cs
  Assets/Scripts/SelectCookieBtn.cs
  Assets/Scripts/UI/CookieSelectShop.cs
  Assets/Scripts/UI/LobbyUIManager.cs
Labels: client

#69 닉네임 중복 확인 기능 추가
  Assets/Scenes/Title.unity
  Assets/Scripts/Auth/CreateUser.cs
  Assets/Scripts/DTO/AuthServer/UserInfo.cs
Labels: enhancement

#72 ui 크기 조정
  Assets/Prefabs/UI/Login Canvas.prefab
  Assets/Scenes/Title.unity
Labels: Design

#77 우편 리스트 조회
  Assets/Scenes/LobbyScene.unity
  Assets/Scripts/DTO/Mail.cs
  Assets/Scripts/UI/LobbyUIManager.cs
  Assets/Scripts/UI/MailBox.cs
Labels: client

#87 버그 수정
  Assets/Scenes/LobbyScene.unity
  Assets/Scripts/ExpBarControll.cs
Labels: client

#91 씬 전환 시 플레이어 상태 초기화, 레벨 업, 경험치 UI 수정
  Assets/Scenes/TestMap.unity
  Assets/Scripts/BackgroundScrolling.cs
  Assets/Scripts/DAO.meta
  Assets/Scripts/DAO/GameServer.meta
  Assets/Scripts/DAO/GameServer/Friend.meta
  Assets/Scripts/DAO/GameServer/Friend/FriendList_DAO.cs.meta
  Assets/Scripts/DAO/GameServer/Friend/FriendRequestList_DAO.cs.meta
  Assets/Scripts/DTO/GameResult.cs
  Assets/Scripts/ExpBarControll.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/LoadSceneManager.cs
  Assets/Scripts/PlayerLogic/Player.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: client
